sudo: required

services:
- docker

script:
- make image

before_deploy:
- docker login -u '$(shell echo $$DOCKER_USER)' -p '$(shell echo $$DOCKER_PASS)'

deploy:
- provider: script
  script: make push
  on:
    branch: master
    tags: true
